name: Main workflow

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    uses: bgd-labs/github-workflows/.github/workflows/foundry-test.yml@d9aeed6c047dcb364fb2134d788691ea825ca9ea
    with:
      testCommand: make test
